# Generated by Django 6.0.6 on 2026-07-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "base_fee",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "price_per_km",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=8),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="requests_app.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Record",
                "db_table": "cadts_billing",
            },
        ),
    ]
