# Generated by Django 6.0.6 on 2026-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="pickup_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="pickup_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
